### PR TITLE
Jonny

### PR DESCRIPTION
**Pull request by jonny5891**
created code for task 1-3

### CODE REVIEW

**Review by srestr53 — APPROVED** [review]
Looks Good Jonny

**Comment by hayrunnisa00** [comment]
good job

**Review by jonny5891 — COMMENTED** [review]
Please Review

**Review by Firyuza12 — APPROVED** [review]

**Review by Lokmanbzd — APPROVED** [review]
good job

**Review by srestr53 — APPROVED** [review]
looks good Jonny

**Review by hayrunnisa00 — APPROVED** [review]

**Pull request merged**
