### PR TITLE
Created Task1_Solution.java

### PR DESCRIPTION
**Pull request by Firyuza12**

### CODE REVIEW

**Comment by hayrunnisa00** [comment]
cool

**Review by srestr53 — APPROVED** [review]
looks good

**Review by Lokmanbzd — APPROVED** [review]
great job

**Review by jonny5891 — APPROVED** [review]
Approved

**Review by jonny5891 — APPROVED** [review]

**Review by jonny5891 — APPROVED** [review]

**Review by jonny5891 — APPROVED** [review]

**Review by jonny5891 — APPROVED** [review]

**Review by hayrunnisa00 — APPROVED** [review]

**Pull request merged**
